Repository etherdata-blockchain/etherdata-sdk, pull requests merged in 2022-03, with the labels that each got.

#4 fix: release kotlin
  .github/workflows/release.yaml
  package.json
  sdk-dist/kotlin/update-version.js
  yarn.lock
Labels: conventional: bugfix

#10 feat: update mui version to v5
  .github/workflows/pr.yaml
  .release-it.json
  etd-sdk-generator/src/sdk-generator/templates/react/functionTemplate.j2
  etd-sdk-generator/src/sdk-generator/templates/react/methodTemplate.j2
  sdk-dist/etd-react-ui/.eslintrc
  sdk-dist/etd-react-ui/example/package.json
  sdk-dist/etd-react-ui/example/src/App.tsx
  sdk-dist/etd-react-ui/example/yarn.lock
  sdk-dist/etd-react-ui/package.json
  sdk-dist/etd-react-ui/src/admin.tsx
  sdk-dist/etd-react-ui/src/clique.tsx
  sdk-dist/etd-react-ui/src/debug.tsx
  sdk-dist/etd-react-ui/src/etd.tsx
  sdk-dist/etd-react-ui/src/json_rpc.tsx
  sdk-dist/etd-react-ui/src/json_rpc_methods.tsx
  sdk-dist/etd-react-ui/src/miner.tsx
  sdk-dist/etd-react-ui/src/personal.tsx
  sdk-dist/etd-react-ui/src/real_time.tsx
  sdk-dist/etd-react-ui/src/txpool.tsx
  sdk-dist/etd-react-ui/yarn.lock
  sdk-dist/kotlin/build.gradle
  sdk-dist/kotlin/src/main/kotlin/com/etd/admin.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/clique.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/constant/constant.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/debug.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/etd.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/files/file.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/json_rpc.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/json_rpc_methods.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/miner.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/personal.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/real_time.kt
  sdk-dist/kotlin/src/main/kotlin/com/etd/txpool.kt
Labels: enhancement

#11 fix: remove unused dep
  sdk-dist/etd-react-ui/package.json
Labels: bug

#14 fix: add bump version
  .release-it.json
  bump-version.js
  sdk-dist/python/update-version.js
Labels: bug

#15 fix: Python Repo URL
  sdk-dist/python/setup.py
Labels: bug

#16 fix: python import problem
  .gitignore
  sdk-dist/python/setup.py
  sdk-dist/python/src/__init__.py
  sdk-dist/python/update-version.js
Labels: bug

#17 fix: missing dependencies in Python package
  etd-sdk-generator/src/index.ts
  sdk-dist/python/pyproject.toml
  sdk-dist/python/setup.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/__init__.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/admin.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/clique.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/debug.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/etd.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc_methods.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/miner.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/personal.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/real_time.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/txpool.py
Labels: bug

#18 fix: add python example to python pkg
  .gitignore
  etd-sdk-generator/src/sdk-generator/generators/python_generator.ts
  etd-sdk-generator/src/sdk-generator/templates/python/functionTemplate.j2
  etd-sdk-generator/src/sdk-generator/utils/python_utils.ts
  sdk-dist/python/src/__init__.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/admin.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/clique.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/debug.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/etd.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc_methods.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/miner.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/personal.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/real_time.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/txpool.py
  sdk-dist/python/src/examples/__init__.py
  sdk-dist/python/src/examples/json_rpc_example.py
Labels: bug

#19 fix: python syntax and add auto pep 8 in formatting
  .github/workflows/build-sdk.yml
  .github/workflows/release.yaml
  etd-sdk-generator/src/sdk-generator/generator.ts
  etd-sdk-generator/src/sdk-generator/generators/kotlin_generator.ts
  etd-sdk-generator/src/sdk-generator/generators/python_generator.ts
  etd-sdk-generator/src/sdk-generator/generators/react_ui_generator.ts
  etd-sdk-generator/src/sdk-generator/generators/typescript_generator.ts
  etd-sdk-generator/src/sdk-generator/templates/python/functionTemplate.j2
  etd-sdk-generator/src/sdk-generator/templates/python/libraryTemplate.j2
  etd-sdk-generator/src/sdk-generator/templates/python/methodTemplate.j2
  etd-sdk-generator/src/sdk-generator/utils/filters.ts
  etd-sdk-generator/src/tests/generator.test.ts
  etd-sdk-generator/src/tests/typescript/typescript_generator.test.ts
  etd-sdk-generator/src/tests/utils/filter.test.ts
  sdk-dist/etd-react-ui/src/admin.tsx
  sdk-dist/etd-react-ui/src/clique.tsx
  sdk-dist/etd-react-ui/src/debug.tsx
  sdk-dist/etd-react-ui/src/json_rpc.tsx
  sdk-dist/etd-react-ui/src/json_rpc_methods.tsx
  sdk-dist/etd-react-ui/src/miner.tsx
  sdk-dist/etd-react-ui/src/personal.tsx
  sdk-dist/etd-react-ui/src/real_time.tsx
  sdk-dist/python/src/etherdata_sdk/__init__.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/__init__.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/admin.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/clique.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/debug.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/etd.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc_methods.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/miner.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/personal.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/real_time.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/txpool.py
  sdk-dist/python/src/etherdata_sdk/utils/__init__.py
  sdk-dist/python/src/etherdata_sdk/utils/to_dict.py
  sdk-dist/python/src/examples/json_rpc_example.py
  sdk-dist/python/src/tests/__init__.py
  sdk-dist/python/src/tests/test_utils.py
Labels: bug

#20 feat: add python documentation
  .github/workflows/build-sdk.yml
  .github/workflows/release.yaml
  docs/docs/intro.md
  docs/docs/python/api/etherdata_sdk/__init__.md
  docs/docs/python/api/etherdata_sdk/json_rpc/admin.md
  docs/docs/python/api/etherdata_sdk/json_rpc/clique.md
  docs/docs/python/api/etherdata_sdk/json_rpc/debug.md
  docs/docs/python/api/etherdata_sdk/json_rpc/etd.md
  docs/docs/python/api/etherdata_sdk/json_rpc/json_rpc.md
  docs/docs/python/api/etherdata_sdk/json_rpc/json_rpc_methods.md
  docs/docs/python/api/etherdata_sdk/json_rpc/miner.md
  docs/docs/python/api/etherdata_sdk/json_rpc/personal.md
  docs/docs/python/api/etherdata_sdk/json_rpc/real_time.md
  docs/docs/python/api/etherdata_sdk/json_rpc/txpool.md
  docs/docs/python/api/etherdata_sdk/utils/__init__.md
  docs/docs/python/api/etherdata_sdk/utils/to_dict.md
  docs/docs/python/api/sidebar.json
  docs/docs/python/intro.md
  docs/docs/typescript/api/classes/Json_rpc_methods.md
  docs/docusaurus.config.js
  docs/i18n/en/code.json
  docs/i18n/en/docusaurus-plugin-content-blog/options.json
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/en/docusaurus-plugin-content-docs/current/intro.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/kotlin/intro.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/python/intro.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/typescript/intro.md
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/package.json
  etd-sdk-generator/src/sdk-generator/generator.ts
  etd-sdk-generator/src/sdk-generator/generators/python_generator.ts
  etd-sdk-generator/src/sdk-generator/templates/python/functionTemplate.j2
  sdk-dist/etd-react-ui/src/json_rpc_methods.tsx
  sdk-dist/kotlin/src/main/kotlin/com/etd/json_rpc_methods.kt
  sdk-dist/python/generator.py
  sdk-dist/python/requirements.txt
  sdk-dist/python/src/etherdata_sdk/json_rpc/admin.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/clique.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/debug.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc_methods.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/miner.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/personal.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/real_time.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/txpool.py
  sdk-dist/python/src/etherdata_sdk/utils/to_dict.py
  sdk-dist/typescript/lib/json_rpc_methods.ts
  sdk/json_rpc_methods.yml
Labels: enhancement

#21 fix: python code's error
  etd-sdk-generator/src/sdk-generator/generators/python_generator.ts
  etd-sdk-generator/src/sdk-generator/templates/python/functionTemplate.j2
  etd-sdk-generator/src/tests/python/python.test.ts
  sdk-dist/etd-react-ui/src/json_rpc_methods.tsx
  sdk-dist/kotlin/src/main/kotlin/com/etd/json_rpc_methods.kt
  sdk-dist/python/src/etherdata_sdk/json_rpc/admin.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/debug.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc_methods.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/personal.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/real_time.py
  sdk-dist/typescript/lib/json_rpc_methods.ts
  sdk/json_rpc_methods.yml
Labels: bug

#22 fix: add upload function
  .github/workflows/release.yaml
  docs/docs/python/api/etherdata_sdk/file/api.md
  docs/docs/python/api/etherdata_sdk/file/download.md
  docs/docs/python/api/etherdata_sdk/file/file.md
  docs/docs/python/api/etherdata_sdk/file/upload_create.md
  docs/docs/python/api/etherdata_sdk/json_rpc/admin.md
  docs/docs/python/api/etherdata_sdk/json_rpc/debug.md
  docs/docs/python/api/etherdata_sdk/json_rpc/json_rpc_methods.md
  docs/docs/python/api/etherdata_sdk/json_rpc/personal.md
  docs/docs/python/api/etherdata_sdk/json_rpc/real_time.md
  docs/docs/python/api/sidebar.json
  docs/docusaurus.config.js
  sdk-dist/python/requirements.txt
  sdk-dist/python/src/etherdata_sdk/file/__init__.py
  sdk-dist/python/src/etherdata_sdk/file/api.py
  sdk-dist/python/src/etherdata_sdk/file/download.py
  sdk-dist/python/src/etherdata_sdk/file/file.py
  sdk-dist/python/src/etherdata_sdk/file/upload_create.py
  sdk-dist/python/src/examples/file_example.py
  sdk-dist/python/src/tests/test_api.py
Labels: bug

#23 fix: add signing function
  .github/workflows/build-sdk.yml
  docs/docs/python/api/etherdata_sdk/account/create.md
  docs/docs/python/api/etherdata_sdk/account/save.md
  docs/docs/python/api/etherdata_sdk/account/sign.md
  docs/docs/python/api/sidebar.json
  sdk-dist/python/requirements.txt
  sdk-dist/python/setup.py
  sdk-dist/python/src/etherdata_sdk/__init__.py
  sdk-dist/python/src/etherdata_sdk/account/__init__.py
  sdk-dist/python/src/etherdata_sdk/account/account.py
  sdk-dist/python/src/etherdata_sdk/account/api.py
  sdk-dist/python/src/etherdata_sdk/account/create.py
  sdk-dist/python/src/etherdata_sdk/account/save.py
  sdk-dist/python/src/etherdata_sdk/account/sign.py
  sdk-dist/python/src/tests/test_account.py
Labels: bug

#24 fix: add tutorial docs for python
  docs/docs/python/tutorial/sign.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/python/tutorial/sign.md
Labels: bug

#25 fix: edit link now contains /tree/main
  docs/docusaurus.config.js
Labels: bug

#27 fix: docs' import
  docs/docs/python/tutorial/sign.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/python/tutorial/sign.md
  sdk-dist/python/src/examples/json_rpc_example.py
Labels: bug

#30 fix: github release script
  .github/workflows/release.yaml
  sdk-dist/kotlin/build.gradle
Labels: bug

#31 fix: missing username in release action
  .github/workflows/release.yaml
Labels: bug

#32 fix: add GitHub Package release in action
  .github/workflows/release.yaml
  sdk-dist/etd-react-ui/package.json
  sdk-dist/typescript/package.json
Labels: bug

#33 fix: publish scope to public in action
  .github/workflows/release.yaml
Labels: bug

#34 feat: add python download function
  docs/docs/python/api/etherdata_sdk/file/file.md
  docs/docs/python/api/etherdata_sdk/file/upload_create.md
  sdk-dist/python/requirements.txt
  sdk-dist/python/src/etherdata_sdk/file/file.py
  sdk-dist/python/src/etherdata_sdk/file/upload_create.py
  sdk-dist/python/src/etherdata_sdk/types.py
  sdk-dist/python/src/examples/file_example.py
  sdk-dist/python/src/examples/json_rpc_example.py
  sdk-dist/python/src/tests/test_file.py
Labels: enhancement

#35 fix: add more docs to python tutorial
  docs/docs/python/tutorial/file.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/python/tutorial/file.md
Labels: bug

#36 fix: python save error
  sdk-dist/python/.gitignore
  sdk-dist/python/src/etherdata_sdk/account/api.py
  sdk-dist/python/src/etherdata_sdk/account/save.py
  sdk-dist/python/src/tests/test_account.py
Labels: bug

#37 fix: python rpc method won't throw proper error message
  etd-sdk-generator/src/sdk-generator/generators/python_generator.ts
  etd-sdk-generator/src/sdk-generator/templates/python/methodTemplate.j2
  sdk-dist/python/src/etherdata_sdk/exception/__init__.py
  sdk-dist/python/src/etherdata_sdk/exception/rpc.py
  sdk-dist/python/src/etherdata_sdk/file/upload_create.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/admin.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/clique.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/debug.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/etd.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/json_rpc_methods.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/miner.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/personal.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/real_time.py
  sdk-dist/python/src/etherdata_sdk/json_rpc/txpool.py
  sdk-dist/python/src/tests/test_json_rpc.py
Labels: bug
